export const DEMO_DOCTOR_ID = '00000000-0000-4000-8000-000000000001';
export const TEST_PHONE = '+919876543210';
export const TEST_LOGIN_CODE = '1234';

export const demoProfile = {
  id: DEMO_DOCTOR_ID,
  phone_number: TEST_PHONE,
  display_name: 'Dr. Ritish Reddy',
  username: 'dr.ritishreddy',
  slug: 'dr-ritish-reddy',
  specialty: 'Gastroenterology',
  hospital_name: 'Asian Hospitals',
  experience_years: 8,
  qualifications: 'MBBS, MD, DM – Gastroenterology',
  city: 'Hyderabad',
  registration_number: '',
  bio: 'Gastroenterologist focused on digestive health, liver care and practical guidance patients can understand.',
  avatar_url: '',
  follower_count: 2840,
};

export const demoPosts = [
  {
    id: 'demo-post-1',
    doctor_phone: TEST_PHONE,
    title: '3 signs your gut needs more attention',
    caption: 'Persistent bloating, discomfort after meals and sudden bowel changes deserve a thoughtful review—not guesswork.',
    hashtags: ['GutHealth', 'Gastroenterology', 'DigestiveHealth'],
    media_type: 'image',
    media_url: '',
    status: 'published',
    views_count: 18420,
    likes_count: 3210,
    comments_count: 186,
    published_at: '2026-08-10T06:30:00.000Z',
    created_at: '2026-08-10T06:30:00.000Z',
  },
  {
    id: 'demo-post-2',
    doctor_phone: TEST_PHONE,
    title: 'Acidity: what to change before dinner',
    caption: 'Try an earlier, lighter dinner and leave enough time before lying down. Small timing changes can reduce reflux symptoms.',
    hashtags: ['Acidity', 'Reflux', 'DigestiveCare'],
    media_type: 'video',
    media_url: '',
    status: 'published',
    views_count: 8640,
    likes_count: 5920,
    comments_count: 84,
    published_at: '2026-08-11T08:15:00.000Z',
    created_at: '2026-08-11T08:15:00.000Z',
  },
  {
    id: 'demo-post-3',
    doctor_phone: TEST_PHONE,
    title: 'A simple liver-friendly plate',
    caption: 'Use this plate guide to make everyday meals easier on your liver.',
    hashtags: ['LiverHealth', 'HealthyPlate'],
    media_type: 'image',
    media_url: '',
    status: 'draft',
    views_count: 0,
    likes_count: 0,
    comments_count: 0,
    published_at: null,
    created_at: '2026-08-11T10:00:00.000Z',
  },
];
