export const DEMO_DOCTOR_ID = '00000000-0000-4000-8000-000000000001';

export const demoProfile = {
  id: DEMO_DOCTOR_ID,
  display_name: 'Dr. Priya Mehta',
  username: 'drpriyamehta',
  specialty: 'Nutritionist',
  qualifications: 'MBBS, MSc Clinical Nutrition',
  registration_number: '',
  bio: 'Helping families build healthier habits through clear, evidence-led guidance.',
  avatar_url: '',
  follower_count: 12480,
};

export const demoPosts = [
  {
    id: 'demo-post-1',
    title: '5 morning stretches to boost your energy',
    caption: 'Start your day with gentle stretches that improve mobility and support overall wellbeing.',
    hashtags: ['MorningRoutine', 'HealthyHabits', 'Wellness'],
    media_type: 'image',
    media_url: '',
    status: 'published',
    views_count: 18240,
    likes_count: 12500,
    comments_count: 128,
    published_at: '2026-08-10T06:30:00.000Z',
    created_at: '2026-08-10T06:30:00.000Z',
  },
  {
    id: 'demo-post-2',
    title: 'Understanding your daily protein needs',
    caption: 'A simple guide to building a balanced plate without overcomplicating your meals.',
    hashtags: ['Nutrition', 'Protein', 'HealthyPlate'],
    media_type: 'video',
    media_url: '',
    status: 'published',
    views_count: 8640,
    likes_count: 5920,
    comments_count: 84,
    published_at: '2026-08-11T08:15:00.000Z',
    created_at: '2026-08-11T08:15:00.000Z',
  },
  {
    id: 'demo-post-3',
    title: 'Three easy hydration reminders',
    caption: 'Small cues that help you drink water consistently through a busy clinic day.',
    hashtags: ['Hydration', 'DailyHealth'],
    media_type: 'image',
    media_url: '',
    status: 'draft',
    views_count: 0,
    likes_count: 0,
    comments_count: 0,
    published_at: null,
    created_at: '2026-08-11T10:00:00.000Z',
  },
];
